### ISSUE TITLE
CPU usage is excessive on a pi0

### ISSUE THREAD

**Issue by saket424** [roscoe81/northcliff_spl_monitor#1]
@roscoe81 
Thanks for sharing this project. Wonderful initiative . I truly think sound is the sleeper sensor and is very useful especially when it comes to public safety applications.

Have you looked at optimizing the CPU usage . The script seems to be working and I see lively spikes in SPL when I clap or yell but I am seeing 80% CPU usage on my dinky little pi0 which has to do other tasks besides SPL measurment

I am using the latest 2.9 version. Was 2.1 version more gentle on the CPU usage. What if I am not interested in the frequency histogram, would that save a lot of CPU? 

I think saving some recordings loud clips (when a dB level is exceeded) off for future analysis implemented as a circular buffer sounds very useful. Any thoughts on that ?

**Comment by saket424** [comment]
Just for another data point

https://github.com/TheHWcave/Enviro-Plus/blob/master/review-part2/micro_SPL.py consumes roughly 15% of the CPU

**Comment by roscoe81** [comment]
Thanks for the feedback @saket424 

I haven't really focused on optimising CPU usage. The frequency histogram doesn't add to the CPU load unless that display is used, so I don't expect that to make a difference.

You might like to try adding your other tasks in the main loop to see if that makes a difference. I have done similar when integrating SPL into my [Enviro Monitor](https://github.com/roscoe81/enviro-monitor) and the CPU usage is running at around 50% in that code.

The code in the other data point that you posted might result in a lower CPU load because it seems to sample at 22kHz (mine does 48kHz) with 1 second chunks (mine does 250ms chunks) and doesn't seem to undertake any A-weighting compensation. In my view, those compromises might reduce CPU load but all impact the accuracy of the noise measurements.
